# Generated by Django 3.1 on 2020-08-08 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=45)),
                ('numeroTVA', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Clients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_facture', models.AutoField(primary_key=True, serialize=False)),
                ('dateFacturation', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=11)),
                ('nomDeFichier', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'Factures',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=45)),
                ('numeroTVA', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Fournisseurs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=150)),
                ('firstName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserTiersFacture',
            fields=[
                ('id_userFacture', models.AutoField(primary_key=True, serialize=False)),
                ('id_client', models.ForeignKey(blank=True, db_column='id_cient', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='InvoiceBook.client')),
                ('id_facture', models.ForeignKey(db_column='id_facture', on_delete=django.db.models.deletion.DO_NOTHING, to='InvoiceBook.facture')),
                ('id_fournisseur', models.ForeignKey(blank=True, db_column='id_fournisseur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='InvoiceBook.fournisseur')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='InvoiceBook.user')),
            ],
            options={
                'db_table': 'UserFactures',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserFournisseur',
            fields=[
                ('id_userFournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('id_fournisseur', models.ForeignKey(db_column='id_fournisseur', on_delete=django.db.models.deletion.DO_NOTHING, to='InvoiceBook.fournisseur')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='InvoiceBook.user')),
            ],
            options={
                'db_table': 'UserFournisseurs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserClient',
            fields=[
                ('id_userClient', models.AutoField(primary_key=True, serialize=False)),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.DO_NOTHING, to='InvoiceBook.client')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='InvoiceBook.user')),
            ],
            options={
                'db_table': 'UserClients',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('e', 'm', 'a', 'i', 'l'), name='unique_email'),
        ),
        migrations.AlterUniqueTogether(
            name='fournisseur',
            unique_together={('nom', 'numeroTVA')},
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('nom', 'numeroTVA')},
        ),
    ]
