# Generated by Django 3.1 on 2020-08-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceBook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='client',
            name='lastname',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='client',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('firstname', 'lastname', 'TVA_number')},
        ),
    ]
