# Generated by Django 3.0.7 on 2020-07-29 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceBook', '0002_auto_20200729_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='id_Client',
            field=models.ForeignKey(blank=True, db_column='id_Cient', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='InvoiceBook.Client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='id_Fournisseur',
            field=models.ForeignKey(blank=True, db_column='id_Fournisseur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='InvoiceBook.Fournisseur'),
        ),
    ]
