# Generated by Django 3.1 on 2020-08-28 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceBook', '0002_auto_20200827_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfacture',
            name='id_facture',
        ),
        migrations.RemoveField(
            model_name='userfacture',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='userfournisseur',
            name='id_fournisseur',
        ),
        migrations.RemoveField(
            model_name='userfournisseur',
            name='id_user',
        ),
        migrations.AddField(
            model_name='client',
            name='id_user',
            field=models.ForeignKey(db_column='id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='id_user',
            field=models.ForeignKey(db_column='id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='numFacture',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='id_user',
            field=models.ForeignKey(db_column='id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facture',
            name='id_client',
            field=models.ForeignKey(blank=True, db_column='id_client', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='InvoiceBook.client'),
        ),
        migrations.DeleteModel(
            name='UserClient',
        ),
        migrations.DeleteModel(
            name='UserFacture',
        ),
        migrations.DeleteModel(
            name='UserFournisseur',
        ),
    ]
